####### Base Config #######
  baseURL = "https://semweb.youronly.one/"                    # .Site.BaseURL
  title = "Semantic Web for Hugo"                # .Site.Title; IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  copyright = ""                                          # .Site.Copyright; leave empty and uncommented to override theme default; we are using our own footer
  timeZone = "Etc/UTC"

####### Site settings #######
  #footnoteAnchorPrefix = ""                              # prefix for footnote anchors
  footnoteReturnLinkContents = "⤴️"                        # text to display for footnote return links
  #paginate = 8
  #paginatePath = "page"                                  # https://example.com/page/2
  rssLimit = 100
  summaryLength = 100                                     # default: 70

  #### Other settings ####
    #disqusShortname = "youronlyone"                       # .Site.DisqusShortname
    #googleAnalytics = ""                     # .Site.GoogleAnalytics



####### Backend settings #######
  canonifyURLs = true                                     # true for our use-case
  #disableAliases = true                                  # use this if we want to use server redirects
  enableEmoji = true                                      # format :smile:
  enableGitInfo = false                                   # it is in Git time
  relativeURLs = false                                    # false for our use-case; make all relative URLs relative to content root
  refLinksNotFoundURL = "https://semweb.youronlyone.one/"

  ## Dev settings ##
    publishDir = "public"
    enableMissingTranslationPlaceholders = true

  ## Other settings ##
    disableKinds = ["robotsTXT", "taxonomyTerm"]

#### LANG stuff ####
  defaultContentLanguage = "en"
  defaultContentLanguageInSubdir = false
  hasCJKLanguage = true
  languageCode = "en"


#######  #######  #######  #######  #######  #######  #######  #######
