# see: https://gohugo.io/content-management/image-processing/
anchor = "Smart"                                  # default: Smart
bgColor = "#ffffff"                               # default: #ffffff; if transparency is not supported
hint = "photo"                                    # default: photo; WebP
quality = 50                                      # default: 75; JPEG and WebP
resampleFilter = "MitchellNetravali"              # default: Box

# see: https://gohugo.io/content-management/image-processing/#exif-data
[exif]
  disableDate = false                             # default: false
  disableLatLong = false                          # default: false
  excludeFields = ""                              # default: ""; performance and cache size
  includeFields = ""                              # default: ""; performance and cache size
