### Info: https://gohugo.io/content-management/multilingual/#configure-languages

[en]
  languageName = "English"
  languageCode = "en"
  #languageCodeCountry = "DO_NOT_USE"
  timeZone = "Etc/UTC"
  weight = 110
  [en.params]
    languageFlag = "ğŸ‡¬ğŸ‡§"

#[en-ph]
  #languageName = "English (PH)"
  #languageCodeCountry = "ph"
  #timeZone = "Asia/Manila"
  #weight = 111
  #[en-ph.params]
    #languageFlag = "ğŸ‡µğŸ‡­"

#[fil]
  #languageName = "Filipino"
  #languageCode = "fil"
  #languageCodeCountry = "ph"
  #timeZone = "Asia/Manila"
  #weight = 120
  #title = ""
  #[fil.params]
    #languageFlag = "ğŸ‡µğŸ‡­"
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[tl-tglg]
  #languageName = "Tagalog Baybayin"
  #languageCode = "tl-Tglg"
  #languageCodeCountry = "ph"
  #timeZone = "Asia/Manila"
  #weight = 121
  #title = ""
  #[tl.tglg.params]
    #languageFlag = "ğŸ‡µğŸ‡­"
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hant]
  #languageName = "ä¸­æ–‡ï¼ˆç¹é«”ï¼‰"
  #languageCode = "zh-Hant"
  #languageCodeCountry = "cn"
  #timeZone = "Asia/Shanghai"
  #weight = 130
  #title = ""
  #[zh-hant.params]
    #languageFlag = "ğŸ‡¨ğŸ‡³"
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hans]
  #languageName = "ä¸­æ–‡ï¼ˆç®€ä½“ï¼‰"
  #languageCode = "zh-Hans"
  #languageCodeCountry = "cn"
  #timeZone = "Asia/Shanghai"
  #weight = 131
  #title = ""
  #[zh-hans.params]
    #languageFlag = "ğŸ‡¨ğŸ‡³"
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[ja]
  #languageName = "æ—¥æœ¬èª"
  #languageCode = "ja"
  #languageCodeCountry = "jp"
  #timeZone = "Asia/Tokyo"
  #weight = 140
  #title = ""
  #[ja.params]
    #languageFlag = "ğŸ‡¯ğŸ‡µ"
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[ko]
  #languageName = "í•œêµ­ì–´"
  #languageCode = "ko"
  #languageCodeCountry = "kr"
  #timeZone = "Asia/Seoul"
  #weight = 150
  #title = ""
  #[ko.params]
    #languageFlag = "ğŸ‡°ğŸ‡·"
    #description = ""      # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
